### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by LondonAstro** [rkaczorek/astroberry-server#144]
Problem was failed in 'sudo apt upgrade', had to do the following
sudo apt update
sudo apt upgrade
sudo apt upgrade --fix-missing
sudo apt dist-upgrade

Regards
Paul

**Comment by mgutierrezp** [comment]
I'm also suffering problems with a completely new fresh install of astroberry 2.0.3 and apt upgrade commands. These are the very first commands I run:

# apt-update
[...]
Fetched 13.6 MB in 9s (1,564 kB/s)                                                                                                                                                                                                           
Reading package lists... Done

# apt-get upgrade -y
[...]
Setting up indi-mqtt (1.0.8-1) ...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyindi-client
  Downloading https://files.pythonhosted.org/packages/bd/2b/4b7c43b20e35ea838706a63c86fe321647c19bbc996c49971369b216d6e7/pyindi-client-0.2.7.tar.gz
Building wheels for collected packages: pyindi-client
  Running setup.py bdist_wheel for pyindi-client ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rvkxhryw/pyindi-client/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nu3ofqca --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building '_PyIndi' extension
  swigging indiclientpython.i to indiclientpython_wrap.cpp
  swig -python -v -Wall -c++ -threads -I/usr/include -I/usr/include/libindi -I/usr/local/include/libindi -o indiclientpython_wrap.cpp indiclientpython.i
  indiclientpython.i:37: Error: Unable to find 'indimacros.h'
  indiclientpython.i:43: Error: Unable to find 'indiwidgettraits.h'
  indiclientpython.i:44: Error: Unable to find 'indipropertyview.h'
  Language subdirectory: python
  Search paths:
     ./
     /usr/include/
     /usr/include/libindi/
     /usr/local/include/libindi/
     ./swig_lib/python/
     /usr/share/swig3.0/python/
     ./swig_lib/
     /usr/share/swig3.0/
  Preprocessing...
  error: command 'swig' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyindi-client
  Running setup.py clean for pyindi-client
Failed to build pyindi-client
Installing collected packages: pyindi-client
  Found existing installation: pyindi-client 0.2.5
    Uninstalling pyindi-client-0.2.5:
      Successfully uninstalled pyindi-client-0.2.5
  Running setup.py install for pyindi-client ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rvkxhryw/pyindi-client/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xlgo91q3/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_PyIndi' extension
    swigging indiclientpython.i to indiclientpython_wrap.cpp
    swig -python -v -Wall -c++ -threads -I/usr/include -I/usr/include/libindi -I/usr/local/include/libindi -o indiclientpython_wrap.cpp indiclientpython.i
    indiclientpython.i:37: Error: Unable to find 'indimacros.h'
    indiclientpython.i:43: Error: Unable to find 'indiwidgettraits.h'
    indiclientpython.i:44: Error: Unable to find 'indipropertyview.h'
    Language subdirectory: python
    Search paths:
       ./
       /usr/include/
       /usr/include/libindi/
       /usr/local/include/libindi/
       ./swig_lib/python/
       /usr/share/swig3.0/python/
       ./swig_lib/
       /usr/share/swig3.0/
    Preprocessing...
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of pyindi-client
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rvkxhryw/pyindi-client/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xlgo91q3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-rvkxhryw/pyindi-client/
[...]
Job for gpsd.socket failed.
See "systemctl status gpsd.socket" and "journalctl -xe" for details.
A dependency job for gpsd.service failed. See 'journalctl -xe' for details.
A dependency job for gpsd.service failed. See 'journalctl -xe' for details.
invoke-rc.d: initscript gpsd, action "start" failed.
● gpsd.service - GPS (Global Positioning System) Daemon
   Loaded: loaded (/lib/systemd/system/gpsd.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-07-21 21:39:18 CEST; 1s ago
 Main PID: 13270 (gpsd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/gpsd.service
           └─13270 /usr/sbin/gpsd -n

Jul 21 21:39:18 astroberry systemd[1]: Starting GPS (Global Positioning System) Daemon...
Jul 21 21:39:18 astroberry systemd[1]: Dependency failed for GPS (Global Positioning System) Daemon.
Jul 21 21:39:18 astroberry systemd[1]: gpsd.service: Job gpsd.service/start failed with result 'dependency'.
Jul 21 21:39:19 astroberry systemd[1]: Dependency failed for GPS (Global Positioning System) Daemon.
Jul 21 21:39:19 astroberry systemd[1]: gpsd.service: Job gpsd.service/start failed with result 'dependency'.
dpkg: error processing package gpsd (--configure):
 installed gpsd package post-installation script subprocess returned error exit status 1
Setting up libdns-export1104 (1:9.11.5.P4+dfsg-5.1+deb10u5) ...
Setting up iputils-ping (3:20180629-2+deb10u2) ...
Setting up libxml2:armhf (2.9.4+dfsg1-7+deb10u2) ...
Setting up libqt5concurrent5:armhf (5.11.3+dfsg1-1+rpi1+deb10u4) ...
Setting up vlc-data (3.0.12-0+deb10u1+rpt2) ...
Setting up ccdciel (0.9.75-2382) ...
Setting up indi-mgen (0.1-9) ...
dpkg: dependency problems prevent configuration of astroberry-server-wui:
 astroberry-server-wui depends on gpsd; however:
  Package gpsd is not configured yet.

dpkg: error processing package astroberry-server-wui (--configure):
 dependency problems - leaving unconfigured
[...]
dpkg: dependency problems prevent configuration of astroberry-server-sysmod:
 astroberry-server-sysmod depends on gpsd; however:
  Package gpsd is not configured yet.

dpkg: error processing package astroberry-server-sysmod (--configure):
 dependency problems - leaving unconfigured
Setting up python3-lxml:armhf (4.3.2-1+deb10u3) ...
dpkg: dependency problems prevent configuration of virtualgps:
 virtualgps depends on gpsd; however:
  Package gpsd is not configured yet.
[...]
dpkg: error processing package virtualgps (--configure):
 dependency problems - leaving unconfigured
[...]
dpkg: dependency problems prevent configuration of astroberry-server-full:
 astroberry-server-full depends on astroberry-server-wui; however:
  Package astroberry-server-wui is not configured yet.
 astroberry-server-full depends on astroberry-server-sysmod; however:
  Package astroberry-server-sysmod is not configured yet.
 astroberry-server-full depends on virtualgps; however:
  Package virtualgps is not configured yet.

dpkg: error processing package astroberry-server-full (--configure):
 dependency problems - leaving unconfigured
[...]
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for libvlc-bin:armhf (3.0.12-0+deb10u1+rpt2) ...
Errors were encountered while processing:
 gpsd
 astroberry-server-wui
 astroberry-server-sysmod
 virtualgps
 astroberry-server-full
E: Sub-process /usr/bin/dpkg returned an error code (1)



if I repeat twice:
root@astroberry:~# apt-get upgrade -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libtiffxx5 python-colorzero
Use 'apt autoremove' to remove them.
The following packages have been kept back:
  indi-bin indi-full indi-pentax kstars-bleeding kstars-bleeding-dbg libindi-dev libindi1 oacapture raspberrypi-sys-mods raspberrypi-ui-mods
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
5 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up gpsd (3.17-7+b1) ...
Creating/updating gpsd user account...
Setting up astroberry-server-wui (2.0.7-1) ...
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
Setting up astroberry-server-sysmod (2.0.5-1) ...
Setting up virtualgps (1.1.0) ...
Setting up astroberry-server-full (2.0.3-1) ...
root@astroberry:~# apt-get upgrade -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libtiffxx5 python-colorzero
Use 'apt autoremove' to remove them.
The following packages have been kept back:
  indi-bin indi-full indi-pentax kstars-bleeding kstars-bleeding-dbg libindi-dev libindi1 oacapture raspberrypi-sys-mods raspberrypi-ui-mods
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.





After the (incomplete) upgrade, it results in a weird behaviour on phd2 (I cannot click the 'connect' button in Indi dialog to configure the guidecam, although I don't know if it is related at all, but if I don't apt-get upgrade, phd2 works perfectly)

cheers

**Comment by bbillp** [comment]
Don’t perform the upgrade, 2.0.3 limps without them.  No problems running PHD2 with Celestron AVX & CGX, imaging with Nikon 5600, ZWO ASI178 guiding.    I find it easier to manually control the imaging camera than trying to figure out KSTARS and EKOS.      Bill P.

**Comment by mgutierrezp** [comment]
this is very strange. I've done another test. Installed again from scratch. I did only upgrade PHD2, from 2.6.9 to 2.6.10, and the weird behaviour described above, appears again. PHD2 2.6.9 works perfectly, but when upgraded to 2.9.10 I cannot connect to the guidecam (exposed by the indi server on localhost). When I click on phd2 'connect' button, absolutely nothing happens; although I see error messages (cannot connect) in phd2 logs. I've indeed opened a ticket to phd2 developers **but** I really think it is not a bug of phd2. I have another phd2 2.6.10 installation on my linux desktop (linux mint), and can connect to the indi server in the rpi. Maybe a bug in the phd2 .deb packaging? any ideas?

**Comment by LondonAstro** [comment]
Just to add at the time of the upgrade I got PHD2 2.6.9dev 4, which I was happy with. Plus like Bill I do not define my guide camera (Orion SSAG) in the Indi Server, but directly point PHD2 to it (defined as QHY Camera). The Orion SSAG has been native support in PHD2 for a number of years, but there is definitely some issue with the basic upgrade.

**Comment by rkaczorek** [comment]
@mgutierrezp most problems you are reporting are related to indi-mqtt which depends on extrenal library pyindi-client (python bindings for INDI). It has became unstable recently and the author decided to announce end of life of this library. If you don't use MQTT uninstall indi-mqtt before upgrade. The second problem is related to gpsd. To fix it run the following sequence of commands:
```
sudo systemctl stop gpsd.service
sudo systemctl stop gpsd.socket
sudo dpkg --configure -a
sudo systemctl restart gpsd.service
sudo systemctl restart gpsd.socket
```
I will be releasing clean and updated version 2.0.4 soon. It's a long time since 2.0.3 has been released

**Comment by LondonAstro** [comment]
Great response, I must say how impressed I am with Astroberry, I've been into Astro photography for about 8 years (Windows based) and find this solution easy to install and use. I assume I'm allowed to close the issue....

**Comment by mgutierrezp** [comment]
the workaround described above has worked perfectly. I suspected it was related with ind-mqtt. PHD 2.6.10 is still not working (same behaviour as described). Version 2.6.9 works. Do not know where the problem really is

**Comment by bbillp** [comment]
What are the old and updated Astroberry version numbers ?

**Comment by rkaczorek** [comment]
Old is all below 2.0.3 however packages are updated within the unchanged version. Think of it as updating windows. All fixes and patches do not change windows 10 to anything else.

**Comment by bbillp** [comment]
Thanks for the rapid explanation.  Can you give me the command line to properly update?  My version is about 6 months old.

**Comment by rkaczorek** [comment]
Run ordinary update command i.e. `sudo apt update && sudo apt upgrade`
If there is any issue with the update run the sequence:
```
sudo systemctl stop gpsd.service
sudo systemctl stop gpsd.socket
sudo dpkg --configure -a
sudo systemctl restart gpsd.service
sudo systemctl restart gpsd.socket
```
Then you can run updates without problems

**Comment by bbillp** [comment]
Thank you, I have learned from 6 years Pi experience never to update unless its extremely necessary as I’ve lost use of some good astronomy apps.   I’ll update a backup SD …. Thanks for the info.
