### ISSUE TITLE
INDI 1.8.6 comes from Astroberry.IO

### ISSUE THREAD

**Issue by AradoSKY** [rkaczorek/astroberry-server#93]
Hello,

Using INDI and Raspberry PI, this script confirms that 1.8.6 comes from Astroberry.IO. No path exists to get back to 3rdparty 1.8.5. Please provide access to 1.8.5. 1.8.6 has too many bugs. 

root@astroberry:/home/astroberry/AstroRoot/indi-3rdparty/indi-gpsd# wget -O - https://www.astroberry.io/repo/key | sudo apt-key add -
--2020-08-24 11:49:34--  https://www.astroberry.io/repo/key
Resolving www.astroberry.io (www.astroberry.io)... 87.98.235.184
Connecting to www.astroberry.io (www.astroberry.io)|87.98.235.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4365 (4.3K)
Saving to: ‘STDOUT’

-                                    100%[======================================================================>]   4.26K  --.-KB/s    in 0s      

2020-08-24 11:49:34 (51.2 MB/s) - written to stdout [4365/4365]

OK
root@astroberry:/home/astroberry/AstroRoot/indi-3rdparty/indi-gpsd# sudo su -c "echo 'deb https://www.astroberry.io/repo/ buster main' > /etc/apt/sources.list.d/astroberry.list"
root@astroberry:/home/astroberry/AstroRoot/indi-3rdparty/indi-gpsd# sudo apt install indi-full gsc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gsc is already the newest version (1.3).
indi-full is already the newest version (1.8.6).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@astroberry:/home/astroberry/AstroRoot/indi-3rdparty/indi-gpsd#

**Comment by rkaczorek** [comment]
This is false positive. You cannot judge INDI version based on indi-full package because it is just a meta-package installing all other packages - it has no content by it's own.
Astroberry repository DOES NOT provide INDI 1.8.6 as for now. You can easily verify this by going to https://www.astroberry.io/repo/pool/main/libi/libindi/
The way to verify what version of installed INDI library is to inspect version of libindi1. As you see the latest version provided by Astroberry is 1.8.5
